# 应用名称
spring:
  application:
    name: crud-gen
  main:
    banner-mode: off
  profiles:
    include: config

crud-gen:
  jdbc-ds:
    url: ${cru-gen.datasoure.url}
    user: ${cru-gen.datasoure.user}
    password: ${cru-gen.datasoure.password}
    driver: ${cru-gen.datasoure.driver}
    catalog: ${cru-gen.datasoure.catalog}
    schema-pattern: ${cru-gen.datasoure.schema}
    table-name-pattern: ${cru-gen.datasoure.catalog.table-name}
    column-name-pattern: ${cru-gen.datasoure.catalog.column-name}


  static-data:
    mainPath: ${common.mainPath}
    package: ${common.package}
    moduleName: ${common.moduleName}
    author: ${common.author}

  native-file-receiver:
    output-dir: ${crud-gen.path.packge}

  simple-ts:
    template-dir: ${crud-gen.path.resources}\template
    templates:
      - template-file-path: Controller.java.vm
        target-dir: ${crud-gen.path.packge}\controller
        filename-template: '${className}Controller.java'

      - template-file-path: Service.java.vm
        target-dir: ${crud-gen.path.packge}\service
        filename-template: '${className}Service.java'

      - template-file-path: ServiceImpl.java.vm
        target-dir: ${crud-gen.path.packge}\service\impl
        filename-template: '${className}ServiceImpl.java'

      - template-file-path: Entity.java.vm
        target-dir: ${crud-gen.path.packge}\entity
        filename-template: '${className}.java'

      - template-file-path: Dao.java.vm
        target-dir: ${crud-gen.path.packge}\dao
        filename-template: '${className}Dao.java'

      - template-file-path: mappper.xml.vm
        target-dir: ${crud-gen.path.resources}\mapper
        filename-template: '${className}Mapper.xml'

#      - templateFilePath: add-or-update.vue.vm
#        targetDir: ${crud-gen.path.resources}\vue
#        filename-template: ${table.name.ucc}-add-or-update
#
#      - templateFilePath: index.vue.vm
#        target-dir: ${crud-gen.path.resources}\vue
#        filename-template:
#        static-scope: true
#
#      - templateFilePath: menu.sql.vm
#        target-dir: ${crud-gen.path.resources}\sql
#        filename-template:
