# 应用名称
spring:
  application:
    name: crud-gen
  main:
    banner-mode: off
  profiles:
    #    include: config
    active: config

crud-gen:
  jdbc-data:
    url: ${crud-gen.datasource.url}
    user: ${crud-gen.datasource.user}
    password: ${crud-gen.datasource.password}
    driver: ${crud-gen.datasource.driver}
    catalog: ${crud-gen.datasource.catalog}
    schema-pattern: ${crud-gen.datasource.schema}
    #    table-names: [ user,user_role,role ]
    table-name-pattern: ${crud-gen.datasource.table-name-pattern}
    column-name-pattern: ${crud-gen.datasource.column-name-pattern}

  static-data:
    mainPath: ${crud-gen.mainPath}
    package: ${crud-gen.package}
    moduleName: ${crud-gen.moduleName}
    author: ${crud-gen.author}

  receiver:
    output-dir: ${crud-gen.path.package}

  template:
    template-dir: ${crud-gen.path.template}
    template-files:
      - file-path: Controller.java.vm
        target-dir: ${crud-gen.path.package}/controller
        target-filename: '${className}Controller.java'

      - file-path: Service.java.vm
        target-dir: ${crud-gen.path.package}/service
        target-filename: '${className}Service.java'

      - file-path: ServiceImpl.java.vm
        target-dir: ${crud-gen.path.package}/service/impl
        target-filename: '${className}ServiceImpl.java'

      - file-path: Entity.java.vm
        target-dir: ${crud-gen.path.package}/entity
        target-filename: '${className}Entity.java'

      - file-path: Dao.java.vm
        target-dir: ${crud-gen.path.package}/dao
        target-filename: '${className}Dao.java'

      - file-path: mappper.xml.vm
        target-dir: ${crud-gen.path.resources}/mapper
        target-filename: '${className}Mapper.xml'

#      - file-path: add-or-update.vue.vm
#        target-dir: ${crud-gen.path.resources}/vue
#        target-filename: ${table.name.ucc}-add-or-update
#
#      - file-path: index.vue.vm
#        target-dir: ${crud-gen.path.resources}/vue
#        target-filename:
#        static-template: true
#
#      - file-path: menu.sql.vm
#        target-dir: ${crud-gen.path.resources}/sql
#        target-filename:
